#!/usr/bin/env python3
"""
Convert DW4 NES monsters to DQ4r SNES format (.pasm)
"""

import struct
from pathlib import Path
from typing import List

DW4_ROM_PATH = Path("C:\\Users\\me\\source\\repos\\dragon-warrior-4-info\\roms\\Dragon Warrior IV (1992-10)(Enix)(US).nes")

# NES Bank mapping:
# iNES header: 16 bytes
# PRG-ROM: 32 banks x 16KB
# Bank 6 starts at file offset: 0x10 + (6 * 0x4000) = 0x18010
# CPU address $A2A2 = ROM offset within bank: $A2A2 - $8000 = $2A2A
# File offset: 0x18010 + 0x2A2A = 0x1AA3A

INES_HEADER_SIZE = 0x10
PRG_BANK_SIZE = 0x4000
BANK_6_CPU_ADDR = 0xA2A2
BANK_6_ROM_OFFSET = BANK_6_CPU_ADDR - 0x8000
BANK_6_FILE_OFFSET = INES_HEADER_SIZE + (6 * PRG_BANK_SIZE)

DW4_MONSTER_TABLE_OFFSET = BANK_6_FILE_OFFSET + BANK_6_ROM_OFFSET
DW4_MONSTER_SIZE = 27
DW4_MONSTER_COUNT_APPROX = 195

class DW4Monster:
    """NES DW4 monster (27 bytes)."""
    def __init__(self, data: bytes, offset: int):
        d = data[offset:offset + 27]
        self.exp = struct.unpack_from('<H', d, 0)[0]
        self.gold = struct.unpack_from('<H', d, 2)[0]
        self.hp = struct.unpack_from('<H', d, 4)[0]
        self.atk = d[6]
        self.def_ = d[7]
        self.agi = d[8]
        self.skills = d[9:15]
        self.ai = d[15:19]
        self.drop_id = d[19]
        self.drop_rate = d[23]

def extract_dw4_monsters(rom_path: Path) -> List[DW4Monster]:
    """Extract monsters from DW4 NES ROM using correct offset."""
    with open(rom_path, "rb") as f:
        rom = f.read()
    
    monsters = []
    for i in range(DW4_MONSTER_COUNT_APPROX):
        offset = DW4_MONSTER_TABLE_OFFSET + (i * DW4_MONSTER_SIZE)
        if offset + DW4_MONSTER_SIZE > len(rom):
            break
        
        monster = DW4Monster(rom, offset)
        # Sanity check: HP should be reasonable (1-999)
        if 1 <= monster.hp <= 999:
            monsters.append(monster)
        else:
            # Stop at first invalid HP (likely end of table)
            print(f"Stopping at invalid HP {monster.hp} at offset {offset}")
            break
    
    return monsters

def monsters_to_pasm(monsters: List[DW4Monster], output_path: Path):
    """Generate .pasm file with DW4 monster data in DQ3r format."""
    lines = [
        "; ============================================================================",
        "; DW4 Monster Data (Converted to DQ3r SNES Format)",
        "; ============================================================================",
        "; Auto-generated by dw4_to_dq4r_monsters.py",
        "; Structure: HP(2) EXP(2) Gold(2) ATK(1) DEF(1) AGI(1) DROP_ID(1) DROP_RATE(1)",
        "; ============================================================================",
        "",
        "MONSTER_COUNT = ${:02X}".format(len(monsters)),
        "",
        "MONSTER_TABLE:",
    ]
    
    for i, m in enumerate(monsters):
        lines.append(f"; Monster {i:3d} - HP: {m.hp:3d}, ATK: {m.atk:2d}, DEF: {m.def_:2d}, AGI: {m.agi}")
        lines.append(f"\t.word ${m.hp:04X}\t\t; HP")
        lines.append(f"\t.word ${m.exp:04X}\t\t; Experience")
        lines.append(f"\t.word ${m.gold:04X}\t\t; Gold")
        lines.append(f"\t.byte ${m.atk:02X}\t\t; Attack")
        lines.append(f"\t.byte ${m.def_:02X}\t\t; Defense")
        lines.append(f"\t.byte ${m.agi:02X}\t\t; Agility")
        lines.append(f"\t.byte ${m.drop_id:02X}\t\t; Drop Item ID")
        lines.append(f"\t.byte ${m.drop_rate:02X}\t\t; Drop Rate")
    
    lines.extend([
        "",
        "MONSTER_TABLE_END:",
    ])
    
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    
    print(f"Generated {output_path} with {len(monsters)} monsters")

def main():
    print("=" * 70)
    print("DW4 to DQ4r Monster Converter")
    print("=" * 70)
    print(f"\nDW4 ROM offset calculation:")
    print(f"  iNES header: 0x{INES_HEADER_SIZE:02X}")
    print(f"  Bank 6 file offset: 0x{BANK_6_FILE_OFFSET:06X}")
    print(f"  CPU address $A2A2, ROM offset: 0x{BANK_6_ROM_OFFSET:04X}")
    print(f"  Monster table file offset: 0x{DW4_MONSTER_TABLE_OFFSET:06X}")
    
    try:
        monsters = extract_dw4_monsters(DW4_ROM_PATH)
        print(f"\nExtracted {len(monsters)} valid monsters")
        
        if monsters:
            print(f"\nFirst few monsters:")
            for i, m in enumerate(monsters[:3]):
                print(f"  {i}: HP={m.hp:3d} ATK={m.atk:2d} DEF={m.def_:2d} AGI={m.agi} EXP={m.exp:4d} Gold={m.gold:4d}")
        
        output = Path("c:\\Users\\me\\source\\repos\\dq4r-info\\src\\data\\monsters_dw4.pasm")
        output.parent.mkdir(parents=True, exist_ok=True)
        monsters_to_pasm(monsters, output)
        
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
